pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'playwright-tests'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Run Playwright Tests') {
            steps {
                sh '''
                    mkdir -p allure-results allure-report test-results
                    docker run --rm \
                      -e CI=true \
                      -v "$WORKSPACE/allure-results:/app/allure-results" \
                      -v "$WORKSPACE/test-results:/app/test-results" \
                      $DOCKER_IMAGE npm run pw:test
                '''
            }
        }

        stage('Generate Allure Report') {
            steps {
                sh '''
                    docker run --rm \
                      -v "$WORKSPACE/allure-results:/app/allure-results" \
                      -v "$WORKSPACE/allure-report:/app/allure-report" \
                      $DOCKER_IMAGE npx allure generate ./allure-results -o ./allure-report --clean
                '''
            }
        }
    }

    post {
        always {
            junit 'test-results/junit.xml'
            allure includeProperties: false, results: [[path: 'allure-results']]
            archiveArtifacts artifacts: 'allure-report/**', allowEmptyArchive: true
        }
    }
}